### PR TITLE
for execise

### PR DESCRIPTION
**Pull request by 205085028**
wonderful！

### CODE REVIEW

**Review by 205085028 — COMMENTED** [review]
oi！

**Comment by Sakura-RaidenMEI** [comment]
why not align（

**Comment by Sakura-RaidenMEI** [comment]
why it's not align(

**Comment by cxy165** [comment]
game description should be [0...2] rather than [1...3]

**Comment by Sakura-RaidenMEI** [comment]
why it's not aligned（

**Comment by cszhengyh** [comment]
good job!

**Comment by smart-lily** [comment]
> why it's not aligned（

my editor help me align automatically. 😄

**Comment by smart-lily** [comment]
> game description should be [0...2] rather than [1...3]

I fixed it.

**Pull request merged**
